image: minio/mc
stages:
  - deploy

staging:
  stage: deploy
  script:
    - rm readme.md
    - mc mb -p minio/sway-me/shared/ui-kit
    - mc cp --recursive *  minio/sway-me/shared/ui-kit 
  only:
    - master
